export const GEO = {
  "Algeria":      { "Northern": ["Algiers","Oran","Constantine","Annaba","Sétif"], "Southern": ["Tamanrasset","Adrar","Ghardaïa","Ouargla"] },
  "Angola":       { "Luanda": ["Belas","Cacuaco","Luanda","Viana"], "Central": ["Bié","Huambo","Huíla"], "Northern": ["Bengo","Cabinda","Uíge"] },
  "Benin":        { "Southern": ["Atlantique","Littoral","Mono","Ouémé"], "Northern": ["Alibori","Atacora","Borgou","Collines"] },
  "Botswana":     { "Southern": ["Gaborone","Kgalagadi","Kweneng"], "Northern": ["Chobe","Francistown","Ngamiland"] },
  "Burkina Faso": { "Central": ["Centre","Centre-Est","Centre-Nord","Centre-Ouest"], "Other": ["Boucle du Mouhoun","Est","Hauts-Bassins","Sahel"] },
  "Burundi":      { "Western": ["Bubanza","Bujumbura","Cibitoke"], "Central": ["Gitega","Muramvya","Ngozi"], "Eastern": ["Cankuzo","Kirundo","Ruyigi"] },
  "Cabo Verde":   { "Northern": ["Santo Antão","São Vicente","Sal"], "Southern": ["Santiago","Fogo","Brava"] },
  "Cameroon":     { "Centre": ["Yaoundé","Mfoundi","Lékié"], "Littoral": ["Douala","Wouri","Moungo"], "West": ["Bafoussam","Menoua","Mifi"], "North": ["Bénoué","Mayo-Rey"] },
  "Central African Republic": { "Western": ["Ombella-M'Poko","Lobaye"], "Eastern": ["Haute-Kotto","Vakaga"] },
  "Chad":         { "Western": ["Lac","Kanem","Hadjer-Lamis"], "Central": ["Chari-Baguirmi","Guéra"], "Southern": ["Logone Occidental","N'Djamena"] },
  "Comoros":      { "Grande Comore": ["Hamahamet","Itsandra","Mitsamiouli"], "Anjouan": ["Domoni","Mutsamudu"], "Mohéli": ["Fomboni"] },
  "Congo":        { "Brazzaville": ["Bacongo","Makélékélé","Poto-Poto"], "Other": ["Bouenza","Kouilou","Niari"] },
  "Côte d'Ivoire": { "Abidjan": ["Abobo","Adjamé","Cocody","Yopougon"], "Other": ["Bouaké","Daloa","San-Pédro","Yamoussoukro"] },
  "DR Congo":     { "Kinshasa": ["Barumbu","Gombe","Kinshasa","Limete","Ngaliema"], "North Kivu": ["Beni","Goma","Lubero"], "South Kivu": ["Bukavu","Fizi","Uvira"], "Katanga": ["Haut-Katanga","Lualaba"] },
  "Djibouti":     { "Djibouti": ["Balbala","Arhiba","Boulaos"], "Regions": ["Ali Sabieh","Arta","Dikhil","Obock","Tadjourah"] },
  "Egypt":        { "Cairo": ["Cairo","Giza","Helwan"], "Northern": ["Alexandria","Beheira","Dakahlia"], "Upper Egypt": ["Asyut","Luxor","Qena","Aswan"] },
  "Equatorial Guinea": { "Bioko": ["Bioko Norte","Bioko Sur"], "Continental": ["Centro Sur","Kié-Ntem","Litoral"] },
  "Eritrea":      { "Zones": ["Central","Anseba","Debub","Gash-Barka","Maekel"] },
  "Eswatini":     { "Districts": ["Hhohho","Lubombo","Manzini","Shiselweni"] },
  "Ethiopia":     { "Addis Ababa": ["Addis Ketema","Bole","Gullele","Yeka"], "Oromia": ["Arsi","Bale","Jimma","West Shewa"], "Amhara": ["East Gojjam","North Gondar","West Gojjam"], "SNNPR": ["Gurage","Hadiya","Sidama","Wolayita"] },
  "Gabon":        { "Provinces": ["Estuaire","Haut-Ogooué","Ngounié","Ogooué-Maritime","Woleu-Ntem"] },
  "Gambia":       { "Divisions": ["Banjul","Kanifing","West Coast","Lower River","North Bank"] },
  "Ghana":        { "Greater Accra": ["Accra Metropolitan","Tema","Ga East","Ga West"], "Ashanti": ["Kumasi Metropolitan","Obuasi","Mampong"], "Northern": ["Tamale","Yendi","Savelugu"], "Western": ["Sekondi Takoradi","Tarkwa"], "Upper East": ["Bolgatanga","Navrongo"], "Upper West": ["Wa","Lawra"] },
  "Guinea":       { "Conakry": ["Ratoma","Matam","Kaloum","Dixinn"], "Regions": ["Boké","Kankan","Labé","Nzérékoré"] },
  "Guinea-Bissau": { "Regions": ["Bafatá","Biombo","Cacheu","Gabú","Oio","Bissau"] },
  "Kenya":        { "Nairobi": ["Dagoretti","Embakasi","Kasarani","Langata","Westlands"], "Rift Valley": ["Baringo","Kajiado","Kericho","Nakuru","Narok","Turkana"], "Central": ["Kiambu","Kirinyaga","Nyeri"], "Eastern": ["Embu","Kitui","Machakos","Meru"], "Western": ["Bungoma","Busia","Kakamega"], "Nyanza": ["Homa Bay","Kisii","Kisumu","Migori"], "Coast": ["Kilifi","Mombasa","Taita Taveta"], "North Eastern": ["Garissa","Mandera","Wajir"] },
  "Lesotho":      { "Districts": ["Berea","Leribe","Mafeteng","Maseru","Mokhotlong"] },
  "Liberia":      { "Counties": ["Bomi","Bong","Grand Bassa","Montserrado","Nimba"] },
  "Libya":        { "Western": ["Tripoli","Zawiyah","Misrata"], "Eastern": ["Benghazi","Derna","Tobruk"], "Southern": ["Sabha","Murzuq"] },
  "Madagascar":   { "Provinces": ["Antananarivo","Antsiranana","Fianarantsoa","Mahajanga","Toamasina"] },
  "Malawi":       { "Northern": ["Chitipa","Karonga","Mzimba"], "Central": ["Dedza","Lilongwe","Kasungu"], "Southern": ["Blantyre","Mangochi","Zomba"] },
  "Mali":         { "Regions": ["Bamako","Gao","Kayes","Koulikoro","Mopti","Ségou","Sikasso"] },
  "Mauritania":   { "Regions": ["Adrar","Brakna","Gorgol","Hodh Ech Chargui","Nouakchott","Trarza"] },
  "Mauritius":    { "Districts": ["Black River","Flacq","Grand Port","Moka","Port Louis","Savanne"] },
  "Morocco":      { "Northern": ["Tanger-Tétouan","Fès-Meknès","Rabat-Salé"], "Central": ["Casablanca-Settat","Marrakech-Safi"], "Southern": ["Souss-Massa","Laâyoune"] },
  "Mozambique":   { "Northern": ["Cabo Delgado","Niassa","Nampula"], "Central": ["Tete","Zambézia","Sofala"], "Southern": ["Inhambane","Gaza","Maputo"] },
  "Namibia":      { "Regions": ["Erongo","Khomas","Kunene","Ohangwena","Oshana","Otjozondjupa"] },
  "Niger":        { "Regions": ["Agadez","Diffa","Dosso","Maradi","Niamey","Tahoua","Zinder"] },
  "Nigeria":      { "Lagos": ["Agege","Alimosho","Apapa","Ikeja","Surulere"], "Kano": ["Fagge","Dala","Gwale","Kano Municipal"], "Rivers": ["Port Harcourt","Obio/Akpor","Eleme"], "Abuja FCT": ["Abaji","Abuja Municipal","Bwari","Gwagwalada"], "Others": ["Adamawa","Akwa Ibom","Anambra","Bauchi","Benue","Borno","Delta","Enugu","Kaduna","Ogun","Oyo","Plateau","Sokoto"] },
  "Rwanda":       { "Kigali": ["Gasabo","Kicukiro","Nyarugenge"], "Northern": ["Burera","Gicumbi","Musanze"], "Southern": ["Huye","Muhanga","Nyanza"], "Eastern": ["Bugesera","Kayonza","Nyagatare"], "Western": ["Karongi","Rubavu","Rusizi"] },
  "São Tomé and Príncipe": { "Islands": ["Água Grande","Cantagalo","Lemba","Príncipe"] },
  "Senegal":      { "Dakar": ["Dakar","Guédiawaye","Pikine","Rufisque"], "Other": ["Diourbel","Fatick","Kaolack","Saint-Louis","Thiès","Ziguinchor"] },
  "Seychelles":   { "Districts": ["Beau Vallon","English River","Grand Anse Mahé","Victoria"] },
  "Sierra Leone": { "Provinces": ["Eastern","Northern","Southern","Western Area"] },
  "Somalia":      { "States": ["Banadir","Galmudug","Jubaland","Puntland","South West","Somaliland"] },
  "South Africa": { "Gauteng": ["Johannesburg","Tshwane","Ekurhuleni"], "Western Cape": ["Cape Town","Drakenstein","Stellenbosch"], "KwaZulu-Natal": ["eThekwini","Amajuba","Zululand"], "Eastern Cape": ["Buffalo City","Nelson Mandela Bay"], "Limpopo": ["Capricorn","Mopani","Vhembe"], "Others": ["Mpumalanga","North West","Northern Cape","Free State"] },
  "South Sudan":  { "States": ["Central Equatoria","Eastern Equatoria","Jonglei","Unity","Upper Nile","Warrap"] },
  "Sudan":        { "States": ["Khartoum","Blue Nile","Gedaref","Gezira","Kassala","Red Sea","White Nile"] },
  "Tanzania":     { "Arusha": ["Arusha Mjini","Arumeru","Karatu","Longido","Monduli","Ngorongoro"], "Dar es Salaam": ["Ilala","Kinondoni","Temeke","Ubungo","Kigamboni"], "Dodoma": ["Bahi","Chamwino","Dodoma Mjini","Kondoa","Mpwapwa"], "Mwanza": ["Ilemela","Kwimba","Magu","Misungwi","Nyamagana","Sengerema","Ukerewe"], "Kilimanjaro": ["Hai","Moshi Mjini","Moshi Vijijini","Mwanga","Rombo","Same"], "Morogoro": ["Gairo","Kilombero","Kilosa","Morogoro Mjini","Mvomero"], "Tanga": ["Handeni","Korogwe","Lushoto","Muheza","Tanga Mjini"], "Other": ["Geita","Iringa","Kagera","Katavi","Kigoma","Lindi","Manyara","Mara","Mbeya","Mtwara","Njombe","Pwani","Ruvuma","Shinyanga","Singida","Tabora"] },
  "Togo":         { "Regions": ["Centrale","Kara","Maritime","Plateaux","Savanes"] },
  "Tunisia":      { "Northern": ["Ariana","Bizerte","Nabeul","Tunis"], "Central": ["Kairouan","Sousse","Sfax"], "Southern": ["Gabès","Médenine","Tataouine"] },
  "Uganda":       { "Central": ["Kampala","Wakiso","Mukono","Masaka"], "Eastern": ["Jinja","Mbale","Soroti","Tororo"], "Northern": ["Gulu","Lira","Arua","Kitgum"], "Western": ["Mbarara","Kabale","Fort Portal","Kasese"] },
  "Zambia":       { "Provinces": ["Central","Copperbelt","Eastern","Luapula","Lusaka","Northern","Southern","Western"] },
  "Zimbabwe":     { "Provinces": ["Bulawayo","Harare","Manicaland","Mashonaland East","Masvingo","Matabeleland"] },
};
